# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,4,100)

array([0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
       0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636,
       0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
       0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677,
       0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697,
       1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717,
       1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
       1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758,
       1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
       1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798,
       2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
       2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838,
       2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
       2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879,
       2.82828283, 2.86868687, 2.90909091, 2.94949495, 2.98989

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.03408862, 0.93125689, 0.54398103, 0.85068382, 0.84130563])

In [23]:
np.random.rand(5,5)

array([[0.59965172, 0.70096991, 0.64444336, 0.998836  , 0.56890803],
       [0.89041786, 0.54549854, 0.23674681, 0.46540982, 0.72024051],
       [0.82872324, 0.25024528, 0.84353172, 0.77525492, 0.6660824 ],
       [0.72340555, 0.08222438, 0.02348252, 0.11357294, 0.90652631],
       [0.43571075, 0.83684367, 0.43035526, 0.22899212, 0.53170257]])

In [25]:
np.random.randn(2) # randn for normal distribution or gaussian distribution

array([-0.93964003,  0.61554475])

In [26]:
np.random.randn(4,4)

array([[-0.91279475,  0.09602396,  0.03467709, -0.92094411],
       [ 0.7910945 , -1.62405267,  0.56480143, -0.68527584],
       [-0.33772616, -0.22263364, -2.26400916, -0.69476109],
       [ 1.51913135,  1.28831603,  0.25576401,  0.24875232]])

In [29]:
np.random.randint(-51,100,10)

array([ 91,  47,  -2,  82, -43,  99,  75,  94, -28, -22])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([ 8, 17, 18, 10, 28, 19, 40, 13, 42, 11])

In [38]:
arr.reshape(5,5) #if is not possible to fill the arr completely (25 elements) you get an error, 
                 #so if intead 5,5 you use 5,4 is error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.max()

24

In [40]:
ranarr.max()

42

In [41]:
ranarr.min()

8

In [42]:
ranarr

array([ 8, 17, 18, 10, 28, 19, 40, 13, 42, 11])

In [44]:
ranarr.argmax() #it returns de index location of the max value

8

In [45]:
ranarr.argmin() #it returns de index location of the min value

0

In [48]:
arr.shape # (25,) indicates this array is just a one dimensional vector

(25,)

In [49]:
arr2 = arr.reshape(5,5)

In [52]:
arr2.shape # (5,5) indicates this array is two dimensional

(5, 5)

In [53]:
arr.dtype

dtype('int32')

In [56]:
from numpy.random import randint # with this yo don't need to write all time np.random.randint, 
                                 # it lets you write just the import, in that case randint

In [57]:
randint(2,10)

6

In [58]:
randint(-51,100,10)

array([ 92, -44,  34,  62,  66, -37,  44,  60,  69,  13])

## Indexing

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[8]

8

In [62]:
arr[1:5]

array([1, 2, 3, 4])

In [63]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [64]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [66]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[0:5] = 100

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
arr = np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
slice_of_arr = arr[0:6]

In [72]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_arr[:] = 99

In [76]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy = arr.copy()

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_copy[:] = 100

In [81]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [82]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [83]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[0][0]

5

In [86]:
arr_2d[0]

array([ 5, 10, 15])

In [87]:
arr_2d[1][1]

25

In [91]:
arr_2d[2][1]  # first bracket is for index rows, and second bracket is for index column. 

40

In [90]:
arr_2d[2,1]  # Double bracket is optional

40

In [95]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [105]:
arr_2d[:2] # remember returns -1

array([[ 5, 10, 15],
       [20, 25, 30]])

In [108]:
arr_2d[1:3]

array([[20, 25, 30],
       [35, 40, 45]])

In [109]:
arr = np.arange(1,11)

In [110]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
bool_arr = arr > 5

In [113]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [115]:
arr[bool_arr]  # it returns just the ones are True

array([ 6,  7,  8,  9, 10])

In [117]:
arr[arr>5] # same in just one line

array([ 6,  7,  8,  9, 10])

In [118]:
arr[arr<3]

array([1, 2])

In [119]:
arr_2d = np.arange(50).reshape(5,10)

In [120]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [125]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Operators

In [126]:
arr = np.arange(0,11)

In [127]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [133]:
arr + 100 #scaler operations

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [134]:
arr * 100 #scaler operations

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [135]:
arr - 100 #scaler operations

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [137]:
arr / arr # 0/0 is a null value (nan)

C:\Users\Sergi\AppData\Local\Temp\ipykernel_3724\749881850.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # 0/0 is a null value (nan)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [140]:
1 / arr  # 1/0 is an infinite value (inf)

C:\Users\Sergi\AppData\Local\Temp\ipykernel_3724\1033710555.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr  # 1/0 is an infinite value (inf)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [144]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [145]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [146]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [147]:
np.max(arr)

10

In [148]:
arr.max()

10

In [149]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [151]:
np.log(arr) # log 0 is infinite (-inf)

C:\Users\Sergi\AppData\Local\Temp\ipykernel_3724\995386163.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # log 0 is infinite


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])